### PR TITLE
Upgrade to Go 1.18

### PR DESCRIPTION
**Pull request by moroten**
Synchronize the dependencies with bb-storage and upgrade to Go 1.18.

### CODE REVIEW

**Comment by moroten** [comment]
The workflow files need to be updated, the existing checks will not work. @EdSchouten, how would you like to proceed?

**Comment by EdSchouten** [comment]
Hey! It looks like you regenerated them and CI is happy. Looks good to merge? 😁

**Comment by moroten** [comment]
Great! I thought GitHub would use the workflow that exists on the master branch and not read from pull requests as users could then add anything in the PR, e.g. printing all secrets to stdout.

**Comment by EdSchouten** [comment]
I think the PR builds don’t depend on secrets. There’s one to push container images, but that only runs post merge.

**Pull request merged**
